name: Fetchwrapper CI

on:
   pull_request:
      branches: [main]
   workflow_dispatch:
      schedule:
         - cron: "0 0 * * *"

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
   build-test:
      strategy:
         matrix:
            os: [ubuntu-latest]
            node-version: [20, 22]
      runs-on: ${{ matrix.os }}

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Setup custom host for mylocal
           run: echo "127.0.0.1 test.zesty.io" | sudo tee -a /etc/hosts

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: ${{ matrix.node-version }}

         - name: Write the .env file
           run: |
              echo '${{ secrets.ENV_FILE }}' > .env

         - name: Install dependencies
           run: npm install

         - name: 🧪 Run unit tests
           run: npm run test

   tests-pass:
      needs: [build-test]

      if: always()
      runs-on: ubuntu-latest
      name: 🚀🚀🚀 Ok to Merge 😎 👍👍👍
      steps:
         - run: exit 1
           if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
